# Generated by Django 5.1.1 on 2024-09-16 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acciones', '0001_initial'),
        ('juntas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accionpurchase',
            name='junta',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='accion_purchases', to='juntas.junta'),
            preserve_default=False,
        ),
    ]
