# Generated by Django 5.1.1 on 2024-09-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acciones', '0002_accionpurchase_junta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accionpurchase',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
