# Generated by Django 5.1.1 on 2024-09-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='junta',
            name='fecha_inicio',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='junta',
            name='periodo',
            field=models.IntegerField(default=1),
        ),
    ]
