# Generated by Django 5.1.1 on 2024-09-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntas', '0002_junta_fecha_inicio_junta_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='junta',
            name='fecha_inicio',
            field=models.DateField(),
        ),
    ]
