# Generated by Django 5.1.1 on 2024-09-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntas', '0003_alter_junta_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='junta',
            name='duration_months',
            field=models.IntegerField(default=12),
        ),
    ]
