# Generated by Django 5.1.1 on 2024-09-17 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('juntas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserva_legal', models.FloatField(default=0.0)),
                ('fondo_social', models.FloatField(default=0.0)),
                ('junta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='juntas.junta')),
            ],
        ),
    ]
