# Generated by Django 5.1.1 on 2024-09-17 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital', '0002_gastocapital_ingresocapital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastocapital',
            name='capital_social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capital.capitalsocial'),
        ),
        migrations.AlterField(
            model_name='gastocapital',
            name='type',
            field=models.CharField(choices=[('Reserva Legal', 'Reserva Legal'), ('Fondo Social', 'Fondo Social')], max_length=255),
        ),
        migrations.AlterField(
            model_name='ingresocapital',
            name='capital_social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capital.capitalsocial'),
        ),
        migrations.AlterField(
            model_name='ingresocapital',
            name='type',
            field=models.CharField(choices=[('Reserva Legal', 'Reserva Legal'), ('Fondo Social', 'Fondo Social')], max_length=255),
        ),
    ]
