# Generated by Django 5.1.1 on 2024-09-16 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('juntas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_interest', models.DecimalField(decimal_places=4, max_digits=5)),
                ('number_of_installments', models.IntegerField()),
                ('approved', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True)),
                ('paid', models.BooleanField(default=False)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_installments', models.IntegerField()),
                ('junta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='juntas.junta')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
