# Generated by Django 5.1.1 on 2024-09-16 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0004_remove_pagosprestamos_monto_cuota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='cuota',
            field=models.IntegerField(default=0),
        ),
    ]
