# Generated by Django 5.1.1 on 2024-09-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0006_alter_prestamo_cuota_alter_prestamo_remaining_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='cuota',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10, null=True),
        ),
    ]
