# Generated by Django 5.1.1 on 2024-09-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0008_alter_prestamo_amount_alter_prestamo_cuota_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='approved',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='fecha_pago',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='fecha_vencimiento',
            field=models.DateField(auto_now=True),
        ),
    ]
