# Generated by Django 5.1.1 on 2024-09-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0009_remove_prestamo_approved_prestamo_fecha_pago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='rejected',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
