# Generated by Django 5.1.1 on 2024-09-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0010_remove_prestamo_rejected_prestamo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
