# Generated by Django 5.1.1 on 2024-09-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0012_remove_prestamo_cuota_prestamo_loan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='monthly_payment',
            field=models.FloatField(null=True),
        ),
    ]
