# Generated by Django 5.1.1 on 2024-09-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0013_prestamo_monthly_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagosprestamos',
            name='custom_amount',
            field=models.FloatField(null=True),
        ),
    ]
