# Generated by Django 5.1.1 on 2024-09-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0014_pagosprestamos_custom_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagosprestamos',
            name='fecha_pago',
            field=models.DateField(),
        ),
    ]
