# Generated by Django 5.1.1 on 2024-09-24 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0016_alter_pagosprestamos_custom_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagosprestamos',
            name='member',
        ),
    ]
