# Generated by Django 5.1.1 on 2024-09-17 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntas', '0001_initial'),
        ('multas', '0002_multa_junta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multa',
            name='junta',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multas', to='juntas.junta'),
        ),
    ]
