# Generated by Django 5.1.1 on 2024-09-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multas', '0005_alter_multa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='multa',
            name='comment',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
