# Generated by Django 5.1.1 on 2024-09-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multas', '0006_multa_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multa',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
