# Generated by Django 5.1.1 on 2024-09-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('FACILITATOR', 'Facilitador'), ('DIRECTOR', 'Directivo'), ('PARTNER', 'Socio')], default='PARTNER', max_length=20),
        ),
    ]
