# Generated by Django 5.1.1 on 2024-09-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role_type',
            field=models.CharField(choices=[('PRESIDENTE', 'Presidente'), ('SECRETARIO', 'Secretario'), ('TESORERO', 'Tesorero'), ('VOCAL', 'Vocal'), ('SOCIO', 'Socio'), ('NONE', 'None')], default='NONE', max_length=20),
        ),
    ]
